# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.team_ranking_text = QtWidgets.QLabel(self.centralwidget)
        self.team_ranking_text.setAlignment(QtCore.Qt.AlignCenter)
        self.team_ranking_text.setObjectName("team_ranking_text")
        self.gridLayout.addWidget(self.team_ranking_text, 15, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.matches_tab = QtWidgets.QWidget()
        self.matches_tab.setObjectName("matches_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.matches_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.matches_list = QtWidgets.QListWidget(self.matches_tab)
        self.matches_list.setObjectName("matches_list")
        self.gridLayout_2.addWidget(self.matches_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.matches_tab, "")
        self.results_tab = QtWidgets.QWidget()
        self.results_tab.setObjectName("results_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.results_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.results_list = QtWidgets.QListWidget(self.results_tab)
        self.results_list.setObjectName("results_list")
        self.gridLayout_3.addWidget(self.results_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.results_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 17, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 1, 1, 5)
        self.t1_name_label = QtWidgets.QLabel(self.centralwidget)
        self.t1_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_name_label.setObjectName("t1_name_label")
        self.gridLayout.addWidget(self.t1_name_label, 6, 1, 1, 1)
        self.t2_name_label = QtWidgets.QLabel(self.centralwidget)
        self.t2_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_name_label.setObjectName("t2_name_label")
        self.gridLayout.addWidget(self.t2_name_label, 6, 5, 1, 1)
        self.vs = QtWidgets.QLabel(self.centralwidget)
        self.vs.setAlignment(QtCore.Qt.AlignCenter)
        self.vs.setObjectName("vs")
        self.gridLayout.addWidget(self.vs, 6, 3, 1, 1)
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t1_image_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_image_label.sizePolicy().hasHeightForWidth())
        self.t1_image_label.setSizePolicy(sizePolicy)
        self.t1_image_label.setMaximumSize(QtCore.QSize(32, 32))
        self.t1_image_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t1_image_label.setText("")
        self.t1_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_image_label.setObjectName("t1_image_label")
        self.horizontalLayout_2.addWidget(self.t1_image_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.t2_image_label = QtWidgets.QLabel(self.centralwidget)
        self.t2_image_label.setMaximumSize(QtCore.QSize(32, 32))
        self.t2_image_label.setText("")
        self.t2_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_image_label.setObjectName("t2_image_label")
        self.horizontalLayout_2.addWidget(self.t2_image_label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 5)
        self.t2_percentage = QtWidgets.QLabel(self.centralwidget)
        self.t2_percentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_percentage.setObjectName("t2_percentage")
        self.gridLayout.addWidget(self.t2_percentage, 14, 5, 1, 1)
        self.t1_ranking = QtWidgets.QLabel(self.centralwidget)
        self.t1_ranking.setObjectName("t1_ranking")
        self.gridLayout.addWidget(self.t1_ranking, 15, 1, 1, 1)
        self.t1_percentage = QtWidgets.QLabel(self.centralwidget)
        self.t1_percentage.setObjectName("t1_percentage")
        self.gridLayout.addWidget(self.t1_percentage, 14, 1, 1, 1)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 1, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 13, 1, 1, 5)
        self.t2_ranking = QtWidgets.QLabel(self.centralwidget)
        self.t2_ranking.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_ranking.setObjectName("t2_ranking")
        self.gridLayout.addWidget(self.t2_ranking, 15, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 448, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 16, 3, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.t1_p1 = QtWidgets.QLabel(self.centralwidget)
        self.t1_p1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t1_p1.setObjectName("t1_p1")
        self.gridLayout_5.addWidget(self.t1_p1, 0, 0, 1, 1)
        self.t1_p4_r = QtWidgets.QLabel(self.centralwidget)
        self.t1_p4_r.setObjectName("t1_p4_r")
        self.gridLayout_5.addWidget(self.t1_p4_r, 3, 1, 1, 1)
        self.t1_p4 = QtWidgets.QLabel(self.centralwidget)
        self.t1_p4.setObjectName("t1_p4")
        self.gridLayout_5.addWidget(self.t1_p4, 3, 0, 1, 1)
        self.t1_p3_r = QtWidgets.QLabel(self.centralwidget)
        self.t1_p3_r.setObjectName("t1_p3_r")
        self.gridLayout_5.addWidget(self.t1_p3_r, 2, 1, 1, 1)
        self.t1_p2_r = QtWidgets.QLabel(self.centralwidget)
        self.t1_p2_r.setObjectName("t1_p2_r")
        self.gridLayout_5.addWidget(self.t1_p2_r, 1, 1, 1, 1)
        self.t1_p2 = QtWidgets.QLabel(self.centralwidget)
        self.t1_p2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t1_p2.setObjectName("t1_p2")
        self.gridLayout_5.addWidget(self.t1_p2, 1, 0, 1, 1)
        self.t1_p1_r = QtWidgets.QLabel(self.centralwidget)
        self.t1_p1_r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t1_p1_r.setObjectName("t1_p1_r")
        self.gridLayout_5.addWidget(self.t1_p1_r, 0, 1, 1, 1)
        self.t1_p3 = QtWidgets.QLabel(self.centralwidget)
        self.t1_p3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t1_p3.setObjectName("t1_p3")
        self.gridLayout_5.addWidget(self.t1_p3, 2, 0, 1, 1)
        self.t1_p5 = QtWidgets.QLabel(self.centralwidget)
        self.t1_p5.setObjectName("t1_p5")
        self.gridLayout_5.addWidget(self.t1_p5, 4, 0, 1, 1)
        self.t1_p5_r = QtWidgets.QLabel(self.centralwidget)
        self.t1_p5_r.setObjectName("t1_p5_r")
        self.gridLayout_5.addWidget(self.t1_p5_r, 4, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 8, 1, 3, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.t2_p1_r = QtWidgets.QLabel(self.centralwidget)
        self.t2_p1_r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p1_r.setObjectName("t2_p1_r")
        self.gridLayout_6.addWidget(self.t2_p1_r, 0, 0, 1, 1)
        self.t2_p4_r = QtWidgets.QLabel(self.centralwidget)
        self.t2_p4_r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p4_r.setObjectName("t2_p4_r")
        self.gridLayout_6.addWidget(self.t2_p4_r, 3, 0, 1, 1)
        self.t2_p2 = QtWidgets.QLabel(self.centralwidget)
        self.t2_p2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t2_p2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t2_p2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p2.setObjectName("t2_p2")
        self.gridLayout_6.addWidget(self.t2_p2, 1, 1, 1, 1)
        self.t2_p3_r = QtWidgets.QLabel(self.centralwidget)
        self.t2_p3_r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p3_r.setObjectName("t2_p3_r")
        self.gridLayout_6.addWidget(self.t2_p3_r, 2, 0, 1, 1)
        self.t2_p2_r = QtWidgets.QLabel(self.centralwidget)
        self.t2_p2_r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p2_r.setObjectName("t2_p2_r")
        self.gridLayout_6.addWidget(self.t2_p2_r, 1, 0, 1, 1)
        self.t2_p3 = QtWidgets.QLabel(self.centralwidget)
        self.t2_p3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t2_p3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t2_p3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p3.setObjectName("t2_p3")
        self.gridLayout_6.addWidget(self.t2_p3, 2, 1, 1, 1)
        self.t2_p4 = QtWidgets.QLabel(self.centralwidget)
        self.t2_p4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t2_p4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t2_p4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p4.setObjectName("t2_p4")
        self.gridLayout_6.addWidget(self.t2_p4, 3, 1, 1, 1)
        self.t2_p1 = QtWidgets.QLabel(self.centralwidget)
        self.t2_p1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t2_p1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t2_p1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p1.setObjectName("t2_p1")
        self.gridLayout_6.addWidget(self.t2_p1, 0, 1, 1, 1)
        self.t2_p5 = QtWidgets.QLabel(self.centralwidget)
        self.t2_p5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t2_p5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t2_p5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p5.setObjectName("t2_p5")
        self.gridLayout_6.addWidget(self.t2_p5, 4, 1, 1, 1)
        self.t2_p5_r = QtWidgets.QLabel(self.centralwidget)
        self.t2_p5_r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_p5_r.setObjectName("t2_p5_r")
        self.gridLayout_6.addWidget(self.t2_p5_r, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 8, 4, 3, 2)
        self.picked_winner_text = QtWidgets.QLabel(self.centralwidget)
        self.picked_winner_text.setAlignment(QtCore.Qt.AlignCenter)
        self.picked_winner_text.setObjectName("picked_winner_text")
        self.gridLayout.addWidget(self.picked_winner_text, 14, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CS bets"))
        self.team_ranking_text.setText(_translate("MainWindow", "Team ranking"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.matches_tab), _translate("MainWindow", "Matches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.results_tab), _translate("MainWindow", "Results"))
        self.t1_name_label.setText(_translate("MainWindow", "Team1"))
        self.t2_name_label.setText(_translate("MainWindow", "Team2"))
        self.vs.setText(_translate("MainWindow", "vs"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.t2_percentage.setText(_translate("MainWindow", "-"))
        self.t1_ranking.setText(_translate("MainWindow", "-"))
        self.t1_percentage.setText(_translate("MainWindow", "-"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.t2_ranking.setText(_translate("MainWindow", "-"))
        self.t1_p1.setText(_translate("MainWindow", "Player1"))
        self.t1_p4_r.setText(_translate("MainWindow", "rating"))
        self.t1_p4.setText(_translate("MainWindow", "Player4"))
        self.t1_p3_r.setText(_translate("MainWindow", "rating"))
        self.t1_p2_r.setText(_translate("MainWindow", "rating"))
        self.t1_p2.setText(_translate("MainWindow", "Player2"))
        self.t1_p1_r.setText(_translate("MainWindow", "rating"))
        self.t1_p3.setText(_translate("MainWindow", "Player3"))
        self.t1_p5.setText(_translate("MainWindow", "Player5"))
        self.t1_p5_r.setText(_translate("MainWindow", "rating"))
        self.t2_p1_r.setText(_translate("MainWindow", "rating"))
        self.t2_p4_r.setText(_translate("MainWindow", "rating"))
        self.t2_p2.setText(_translate("MainWindow", "Player2"))
        self.t2_p3_r.setText(_translate("MainWindow", "rating"))
        self.t2_p2_r.setText(_translate("MainWindow", "rating"))
        self.t2_p3.setText(_translate("MainWindow", "Player3"))
        self.t2_p4.setText(_translate("MainWindow", "Player4"))
        self.t2_p1.setText(_translate("MainWindow", "Player1"))
        self.t2_p5.setText(_translate("MainWindow", "Player5"))
        self.t2_p5_r.setText(_translate("MainWindow", "rating"))
        self.picked_winner_text.setText(_translate("MainWindow", "Winner picked by viewers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

