# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.matches_tab = QtWidgets.QWidget()
        self.matches_tab.setObjectName("matches_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.matches_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.matches_list = QtWidgets.QListWidget(self.matches_tab)
        self.matches_list.setObjectName("matches_list")
        self.gridLayout_2.addWidget(self.matches_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.matches_tab, "")
        self.results_tab = QtWidgets.QWidget()
        self.results_tab.setObjectName("results_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.results_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.results_list = QtWidgets.QListWidget(self.results_tab)
        self.results_list.setObjectName("results_list")
        self.gridLayout_3.addWidget(self.results_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.results_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 6, 1)
        self.vs = QtWidgets.QLabel(self.centralwidget)
        self.vs.setAlignment(QtCore.Qt.AlignCenter)
        self.vs.setObjectName("vs")
        self.gridLayout.addWidget(self.vs, 1, 2, 1, 1)
        self.t2_image_label = QtWidgets.QLabel(self.centralwidget)
        self.t2_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_image_label.setObjectName("t2_image_label")
        self.gridLayout.addWidget(self.t2_image_label, 1, 3, 1, 1)
        self.t1_image_label = QtWidgets.QLabel(self.centralwidget)
        self.t1_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_image_label.setObjectName("t1_image_label")
        self.gridLayout.addWidget(self.t1_image_label, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 448, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 3)
        self.t1_name_label = QtWidgets.QLabel(self.centralwidget)
        self.t1_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_name_label.setObjectName("t1_name_label")
        self.gridLayout.addWidget(self.t1_name_label, 2, 1, 1, 1)
        self.t2_name_label = QtWidgets.QLabel(self.centralwidget)
        self.t2_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_name_label.setObjectName("t2_name_label")
        self.gridLayout.addWidget(self.t2_name_label, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CS bets"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.matches_tab), _translate("MainWindow", "Matches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.results_tab), _translate("MainWindow", "Results"))
        self.vs.setText(_translate("MainWindow", "vs"))
        self.t2_image_label.setText(_translate("MainWindow", "Team2_image"))
        self.t1_image_label.setText(_translate("MainWindow", "Team1_image"))
        self.t1_name_label.setText(_translate("MainWindow", "Team1_name"))
        self.t2_name_label.setText(_translate("MainWindow", "Team2_name"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))

